# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
print(a.sum()) #可以只總和某一軸的元素值
print(np.sum(a)) #把a裡面所有元素值都加起來
print(sum(a)) #若非一維陣列，會是各陣列相對應位置的值相加

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [18]:
A = np.random.random((5, 5))
Amin=A.min()
Amax=A.max()

Anor=(A-Amin)/(Amax-Amin)

print(Anor)

[[0.4988173  0.89592803 0.63198602 0.         0.75100144]
 [0.36552041 1.         0.74948354 0.09249778 0.58879341]
 [0.29670452 0.59181507 0.72204724 0.12674162 0.75389478]
 [0.73157195 0.81675448 0.75551641 0.22771352 0.84762214]
 [0.47938381 0.88823262 0.01734834 0.81601545 0.37645604]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [48]:
A = np.random.randint(1,100,10)
print(A)

Max=np.argmax(A)
A[Max]=-1
print(A)

[65 65  7 67 24 25 68 15 79  2]
[65 65  7 67 24 25 68 15 -1  2]
