# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [1]:
import numpy as np

In [2]:
print(np.zeros((2,3)))
print(np.empty((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
np.zeros 會給出每格初始值皆為0的陣列
np.empty 不需給定初始值，會給出隨機初始值的陣列，裡面並不是資料，而是空間
因為empty是空間，zero給的是數值資料，empty處理速度會比較快

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [3]:
a=np.random.rand(2,3)
b=a*100
c=np.trunc(b)
print(c)

[[69. 90. 16.]
 [20. 75. 89.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [4]:
a=np.random.randint(20,40,size=(2,3))
print(a)

[[31 27 29]
 [39 37 32]]
