In [49]:
import numpy as np

In [51]:
print(np.zeros((2,3)))
print(np.empty((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
np.zeros 會給出每格初始值皆為0的陣列
np.empty 不需給定初始值，會給出隨機初始值的陣列，裡面並不是資料，而是空間
因為empty是空間，zero給的是數值資料，empty處理速度會比較快

In [54]:
a= np.random.random((2,3))
b=a*100
c=np.trunc(b)
print (c)

[[16. 76.  9.]
 [74. 93. 15.]]


In [55]:
a=np.random.randint(20,40,size=(2,3))
print(a)

[[25 34 34]
 [22 25 36]]
